version: '3.4'
x-environment: &environment
  environment:
    - FLASK_DEBUG=1
    - LOG_LEVEL=ERROR

services:
  indoor:
    ports:
      - "5000:5000"
    command:
      - run_dev
    volumes: 
      - .:/var/www/app
    stdin_open: true
    tty: true
    <<: *environment